spring:

  application:
    name: BookHubBack

  datasource:
    url: jdbc:sqlserver://localhost:1433;database=BOOKHUB;encrypt=true;trustServerCertificate=true
    username: sa
    password: Pa$$w0rd

  banner:
    location: file:banner.txt