---
title: BookHub
---
classDiagram
    class User {
        -long id
        -String firstName
        -String lastName
        -String email
        -String password
        -Role role
    }
    class Book {
        -long id
        -String title
        -String author
        -String isbn
        -Category category
        -String shortDesc
        -String longDesc
        -String imgUrl
        -AvailabilityStatus status
        -BookCondition condition
    }
    class AvailabilityStatus {
        <<enumeration>>
        AVAILABLE
        BORROWED
        RESERVED
        BLOCKED
    }
    class BookCondition {
        <<enumeration>>
        PRISTINE
        USED
        POOR
        UNUSABLE
    }
    class Role {
        <<enumeration>>
        MEMBER
        LIBRARIAN
        ADMIN
    }
    class Borrow {
        -long userId
        -long bookId
        -Date borrowStart
        -Date borrowEnd
        -Date returnDate
    }
    class Reservation {
        -long id
        -User user
        -Book book
    }
    class Category {
        -long id
        -String label
    }
