---
title: BookHub
---
classDiagram

    class User {
        -long id
        -String firstName
        -String lastName
        -String email
        -String password
        -Authorities[] authorities
    }
    class Book {
        -long id
        -String title
        -String author
        -String isbn
        -Category category
        -String shortDesc
        -String longDesc
        -String imgUrl
        -BookCondition condition
    }
    class Status {
        <<enumeration>>
        AVAILABLE
        BORROWED
        RESERVED
        BLOCKED
    }
    class BookCondition {
        <<enumeration>>
        PRISTINE
        USED
        POOR
        UNUSABLE
    }
    class Borrow {
        -long borrowerId
        -long bookId
        -Date borrowStart
        -Date borrowEnd
        -Date returnDate
    }
    class Reservation {
        -long id
        -long userId
        -long copyId
    }
    class Category {
        -long id
        -String label
    }
